### ISSUE TITLE
Markup is not respected.

### ISSUE THREAD

**Issue by zulqasar** [pelme/htpy#21]
First and foremost, THANKS for this awesome library.

I am having trouble with Markup. Am I missing out on something?

```py
import htpy as h
from markupsafe import Markup

script = Markup("""
    let editing = document.querySelector('.editing')
""")

btn = h.button(on_click=script)["edit"]

print('script: ', script)
print('btn: ', btn)

>>> script:  let editing = document.querySelector('.editing')
>>> btn:  <button on-click="let editing = document.querySelector(&#39;.editing&#39;)">edit</button>
```

**Comment by pelme** [comment]
This may be a bit confusing at first, but attributes are always escaped, regardless of whether or not it contains markup. This is a feature and this allows you to actually pass HTML fragments or script fragments.

Consider this htpy code:
```py
button(onclick="let name = 'andreas'; alert('hi' + name);")["Say hi"]
```

The value of the attributes is escaped with `&#39;` to avoid breaking the quotes. The browser understands that and parses it as the proper quotes so it all works:
<img width="1022" alt="image" src="https://github.com/pelme/htpy/assets/20529/6ef896ba-f547-4b99-b8de-ce66504683da">

I realized that this behavior is not documented, will add a note to the docs about it!

**Comment by zulqasar** [comment]
Thanks for the quick reply. It addresses my concerns.

**Comment by pelme** [comment]
Reopening this issue until it's documented properly 🙂
