### ISSUE TITLE
Generating tailwind css from htpy

### ISSUE THREAD

**Issue by hudgeon** [pelme/htpy#36]
We currently construct html directly from our python functions using f-strings - so our functions have html strings in them. We then generate our tailwind app.css file with a config that look like this: 

```
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./components/*.py",
		"./components/**/*.py",
	],
```

During our deployment process, the relevant tailwind css file is generated based on the html in the python files.

How should we go about generating our app.css file if we move to htpy?

**Comment by pelme** [comment]
Tailwind is "naive" when it comes to class detection, as long as the classes are words as part of the source file it should be fine: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

Did you try adding a some css classes as htpy code? I think it should just work?

**Comment by hudgeon** [comment]
Amazing! It just works :)

**Comment by pelme** [comment]
Great! Closing the issue since it works. Thinking about how to best document usage examples with different libraries/frameworks. Any ideas or PRs would be appreciated! Also see https://github.com/pelme/htpy/discussions/34 :)
