### ISSUE TITLE
[docs] Adding additional examples?

### ISSUE THREAD

**Issue by maxtheman** [pelme/htpy#69]
Hi there,

I'm using htpy in one of my fastapi projects and I am enjoying it! I was wondering if you're looking for some additional examples? There are some use cases that would be nice to add that I have setup which I could anonymize and put back in the docs, if you're interested.

In particular:
- Using HTMX
- Escaping inline javascript (using clerk.com's sdk for my auth https://github.com/pelme/htpy/issues/62)
- Using forms and inputs (you have a few examples of django forms, but none of just a standard form)
- Tailwind (I am installing this shortly -- googled and [saw that it should just work in the issues](https://github.com/pelme/htpy/issues/36))

Happy to put in a PR, wanted to ask here to see if you had any particular guidance or are going in a new direction with the library which would make such a contribution redundant.

Thank you!

**Comment by pelme** [comment]
Yes please, I think all sorts of examples are welcome! 🙁

**Comment by maxtheman** [comment]
@pelme Cool! Two questions for you:

1. Any preference on having these in separate PRs vs as one big PR?
2. This morning I ended up integrating Tailwind 4, a new release. Unfortunately they have a new auto detection setup for the files there which does not seem to work at all with Python files. I was able to generate a fake js template file automatically from htpy code for vite to pick it up. I wrapped that code up in little package: https://github.com/maxtheman/tailwind_htpy_scanner -- do you want me to mention this package as an aside? Or just mention that Tailwind 3 should "just work" and tailwind 4 will require more configuration and isn't recommended at this time? I hope this makes sense, let me know if this is unclear please!

I can have the PR(s) for you by Saturday.

**Comment by pelme** [comment]
1. Separate PRs would be preferable to make it easier to review/discuss them!
2. I gave tailwind 4 a try and it works for me without any particular configuration, does this work for you?

```
❯ ls
in.css  my_component.py

❯ cat in.css
@import "tailwindcss";

❯ cat my_component.py
import htpy as h

def my_component():
    return h.div('.hue-rotate-180')['tailwind 4!']

❯ npm install tailwindcss@next @tailwindcss/cli@next

added 25 packages in 2s

5 packages are looking for funding
  run `npm fund` for details


❯ node_modules/.bin/tailwindcss -i in.css -o out.css
≈ tailwindcss v4.0.0-beta.7

Done in 133ms
```

hue-rotate-180 is part of the output (but not others such as hue-rotate-90):
```
❯ grep \\.hue-rotate out.css
  .hue-rotate-180 {
```

Documenting how to get going with Tailwind would be nice, regardless of what exact configuration is needed (or not needed) so PRs are very welcome!

**Comment by maxtheman** [comment]
Sounds good. Let me give this a shot @pelme. I came down ill the last few week but will submit individual PRS before the new year.

**Comment by maxtheman** [comment]
Hey @pelme I apologize, I will not be able to complete this at this time. Sorry for using your time, I was excited to contribute but get pulled into non-htpy things. If my situation changes, I'll open those PRs.

**Comment by Ynng** [comment]
Hey @pelme, just for reference:
with Tailwind 4 and htpy, only the last class in something like `h.div('.hue-rotate-180.w-96.h-full')` gets picked up (`h-full`), the rest are ignored and don't make it into out.css
Tested on `@tailwindcss/cli` v4.1.10

**Comment by seichter** [comment]
Just to add here another point of observation. `@tailwindcli` `v4.1.18` with `npm` works as expected as long using `class_` notation. As mentioned by @Ynng dot-notation is not being parsed correctly. 

Micro example:

```python
import htpy
from starlette.applications import Starlette
from starlette.endpoints import HTTPEndpoint
from starlette.responses import HTMLResponse
from starlette.routing import Mount, Route
from starlette.staticfiles import StaticFiles


class Homepage(HTTPEndpoint):
    async def get(self, request):
        title = "Hello World"
        return HTMLResponse(
            htpy.html[
                htpy.head[htpy.title[title]],
                htpy.link(href="/css/output.css", rel="stylesheet"),
                htpy.body[
                    htpy.main[
                        htpy.div(
                            ".hue-rotate-180.w-96.h-full"
                        ),  # dot notation - only last
                        htpy.div(
                            class_=["hue-rotate-180", "w-96", "h-full"]
                        ),  # class_ notation (picked up)
                        htpy.div(class_=["text-3xl", "font-bold", "underline"])[
                            "Hello World!"
                        ],
                    ]
                ],
            ]
        )


app = Starlette(
    routes=[
        Route("/", Homepage),
        Mount(
            "/",
            app=StaticFiles(directory="static"),
            name="static",
        ),
    ]
)
``` 

Further, the Linux binary (installed through AUR)  is so badly maintained and will just bail out with can't find tailwindcss. There is a long thread in the tailwindcss bugtracker with no applicable or failsafe solution. 

Would be great to have an explicit documentation how to get `htpy` working with TailwindCSS.
